### ISSUE TITLE
How fast with CPU?

### ISSUE THREAD

**Issue by pyni** [eric612/MobileNet-SSD-windows#3]
A nice work!
How fast with only CPU ?

**Comment by eric612** [comment]
I add the show message in ssd_detect.cpp

Here was my information : ( i5-4440)

MobileNet-SSD 
Predicted in 0.118000 seconds.

MobileNetV2-SSD 
Predicted in 0.224000 seconds.

The scale and batchnorm layer  of MobileNet-SSD were combined into convolution layer , so it will be faster

**Comment by pyni** [comment]
Thanks for replying

**Comment by eric612** [comment]
I just update DepthwiseConvolution layer to replace group convolution , can speed 4x faster (GPU)

**Comment by pyni** [comment]
well, that is awesome
